import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/MainComponents/Footer";

const inter = Inter({ subsets: ["latin"] });
const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
